version: "3"

volumes:
  postgres-data:

services:
  postgres-db:
    image: postgres:13-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: newpass
      POSTGRES_DB: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask-app:
    build: ../main_app/
    restart: always
    expose:
      - 5000
    depends_on:
      - postgres-db
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg2://newuser:newpass@postgres-db:5432/docker
    command: ["./docker_entrypoints/prod.sh"]

  nginx-proxy:
    build: ./nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask-app
